#!/bin/bash

[ -f zephyr/scripts/requirements.txt ] && pip3 install --user -r zephyr/scripts/requirements.txt
[ -f nrf/scripts/requirements.txt ] && pip3 install --user -r nrf/scripts/requirements.txt
[ -f bootloader/mcuboot/scripts/requirements.txt ] && pip3 install --user -r bootloader/mcuboot/scripts/requirements.txt