name: Publish Docker image

on:
  push:
    branches: [ "main", convco ]
  pull_request:
    branches: [ "main", convco ]
  schedule:
    # “At 04:20 on day-of-month 1.”
    - cron: '20 4 1 * *'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
          
        # Setting up Docker Buildx with docker-container driver is required
        # at the moment to be able to use a subdirectory with Git context
        # See: https://github.com/docker/build-push-action#git-context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Zephyr CI Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: REPOSITORY_URL=https://github.com/zephyrproject-rtos/zephyr
          context: "{{defaultContext}}:zephyr"
          push: true
          tags: ghcr.io/${{ github.repository }}/zephyr-ci:latest,ghcr.io/${{ github.repository }}/zephyr-ci:${{ steps.date.outputs.date }}

      - name: Build and push NCS CI Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: REPOSITORY_URL=https://github.com/nrfconnect/sdk-nrf
          context: "{{defaultContext}}:zephyr"
          push: true
          tags: ghcr.io/${{ github.repository }}/ncs-ci:latest,ghcr.io/${{ github.repository }}/ncs-ci:${{ steps.date.outputs.date }}

      - name: Build and push ConvCo Docker Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:conventional-release"
          push: true
          tags: ghcr.io/${{ github.repository }}/convco:latest,ghcr.io/${{ github.repository }}/convco:${{ steps.date.outputs.date }}